AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'https://fims.store'"

Parameters:
  DBHostParam:
    Type: String
  DBUserParam:
    Type: String
  DBPassParam:
    Type: String
  DBNameParam:
    Type: String

Resources:
  FimaiFunction:
    Type: AWS::Serverless::Function

    Metadata:
      Dockerfile: Dockerfile.lambda
      DockerContext: .

    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["api.fimai.handler"]

      Environment:            # ← must be indented under Properties
        Variables:            # ← exact capitalization
          DB_HOST: !Ref DBHostParam
          DB_USER: !Ref DBUserParam
          DB_PASS: !Ref DBPassParam
          DB_NAME: !Ref DBNameParam

      Events:
        FimaiApi:
          Type: Api
          Properties:
            Path: /api/fimai
            Method: get
        FimaiChatApi:
          Type: Api
          Properties:
            Path: /api/fimai/chat
            Method: post
           